### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by piotrhoppe** [phstc/gesture-translate#5]
Please you should update.

**Comment by phstc** [comment]
Hey @piotrhoppe - Unfortunately Google blocked their Translate API.

But it seems that [gtranslate](https://github.com/bpierre/gtranslate) is accessing it [in a different way that works](https://github.com/bpierre/gtranslate/blob/51d303b3ab199df504190012c9aa11b9855156da/providers/google-translate.js#L36-L43).

Would you be able to submit a PR changing [the way gesture-translate calls Google](https://github.com/phstc/gesture-translate/blob/master/src/chrome/content/gesturegoogtrans/GoogleTranslate.js#L216-L221)?

**Comment by piotrhoppe** [comment]
Ok I will try ;),

2015-05-07 13:52 GMT+02:00 Pablo Cantero <notifications@github.com>:

> Hey @piotrhoppe <https://github.com/piotrhoppe> - Unfortunately Google
> blocked their Translate API.
>
> But it seems that gtranslate <https://github.com/bpierre/gtranslate> is
> accessing it in a different way that works
> <https://github.com/bpierre/gtranslate/blob/51d303b3ab199df504190012c9aa11b9855156da/providers/google-translate.js#L36-L43>
> .
>
> Would you be able to submit a PR changing the way gesture-translate calls
> Google
> <https://github.com/phstc/gesture-translate/blob/master/src/chrome/content/gesturegoogtrans/GoogleTranslate.js#L216-L221>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phstc/gesture-translate/issues/5#issuecomment-99831284>
> .
>



-- 
Piotr Hoppe

**Comment by piotrhoppe** [comment]
I make a change and now I need access to send them.

**Comment by phstc** [comment]
:beers: 

Super awesome! Could you send the changes via a [pull request](https://help.github.com/articles/using-pull-requests/)?

**Comment by piotrhoppe** [comment]
How I can do that? I try "git push" but I don't have access :(

remote: Permission to phstc/gesture-translate.git denied to piotrhoppe.
fatal: unable to access 'https://github.com/phstc/gesture-translate.git/': The requested URL returned error: 403

**Comment by phstc** [comment]
We need to submit a pull request following these steps: https://help.github.com/articles/using-pull-requests/

**Comment by phstc** [comment]
Closed by #6 and #7
